spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8080/seunghwan-db
    username: root
    password: 1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
  session:
    store-type: "jdbc"
    jdbc:
      initialize-schema: embedded
#      schema: classpath:org
      table-name: SPRING_SESSION


server:
  servlet:
    encoding:
      force-response: true
    session:
      timeout: 3600